<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCa4kvtw\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCa4kvtw/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerCa4kvtw.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerCa4kvtw\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerCa4kvtw\appProdProjectContainer([
    'container.build_hash' => 'Ca4kvtw',
    'container.build_id' => '05efa577',
    'container.build_time' => 1615252477,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCa4kvtw');
