<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMndgisd\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMndgisd/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerMndgisd.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerMndgisd\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerMndgisd\appProdProjectContainer([
    'container.build_hash' => 'Mndgisd',
    'container.build_id' => 'f09c47da',
    'container.build_time' => 1616322194,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMndgisd');
